config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: %i[registrations]
  resources :quotes do
    resources :results, param: :uuid, only: %i[show create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'privacypolicy', to: 'static_pages#privacypolicy'
  get 'information', to: 'static_pages#information'
  get '*path', controller: 'application', action: 'render404'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
  mount_uploader :quote_image, QuoteImageUploader
  mount_uploader :opposite_voice, OppositeVoiceUploader
  validates :title, presence: true, uniqueness: true
  validates :emotion, presence: true
  enum emotion: { angry: 0, sad: 1, happy: 2, disgust: 3, surprise: 4, neutral: 5 }
  has_many :results, dependent: :delete_all
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :quote
  mount_uploader :voice_data, VoiceDataUploader

  def score
    parsed_result_message = JSON.parse result_message
    parsed_result_message['emotion_detail'][quote.emotion] * 100
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #if Rails.env.production?
    rescue_from Exception, with: :render500
    rescue_from ActiveRecord::RecordNotFound, with: :render404
  #end

  def render404
    render file: "/app/views/errors/error404.html", status: 404
  end

  def render500(error)
    logger.error(error.message)
    logger.error(error.backtrace.join("\n"))
    render file: "/app/views/errors/error500.html", status: 500
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :update, :edit, :delete]
  before_action :login_scan, only: [:new, :create, :edit, :update]
  before_action :admin_scan, only: [:create, :update]
  def index
    @angry_quotes = Quote.angry
    @sad_quotes = Quote.sad
    @happy_quotes = Quote.happy
    @disgust_quotes = Quote.disgust
    @surprise_quotes = Quote.surprise
    @neutral_quotes = Quote.neutral
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.create(quote_params)
    if @quote.save
      redirect_to quotes_path
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @quote.update(quote_params)
      redirect_to quotes_path
    else
      render :edit
    end
  end

  private

  def quote_params
    params.require(:quote).permit(:title, :quote_image, :opposite_voice, :emotion)
  end

  def set_quote
    @quote = Quote.find(params[:id])
  end

  def login_scan
    unless user_signed_in?
      redirect_to root_path
    end
  end

  def admin_scan
    unless current_user.admin?
      redirect_to root_path
    end
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def show
    @result = Result.find_by(uuid: params[:uuid])
    @display = ResultDisplayService.new(@result).call
  end

  def create
    url = ENV['API_URL']
    voice = File.new(params[:voice_data])
    response = RestClient::Request.execute(
      method: :post,
      url: url,
      payload: {
        multipart: true,
        api_key: ENV['API_KEY'],
        voice_data: voice
      },
      content_type: 'audio/wav'
    )
    result = Result.create(result_params.merge(uuid: SecureRandom.uuid, result_message: response.body))
    render json: { url: quote_result_url(result.quote_id, result.uuid) }
  end

  private

  def result_params
    params.permit(:quote_id, :voice_data)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top; end

  def privacypolicy; end

  def terms; end

  def information; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      site: 'voice-actor-practice',
      title: '声優セリフ練習アプリ',
      reverse: true,
      separator: '|',
      description: 'ひとりでも掛け合いが練習できるアプリ。',
      keywords: '声優',
      canonical: request.original_url,
      noindex: !Rails.env.production?,
      icon: [
        { href: image_url('logo_ogp.jpeg') },
        { href: image_url('logo_ogp.jpeg'), rel: 'apple-touch-icon', sizes: '180x180', type: 'image/jpeg' }
      ],
      og: {
        site_name: 'voice-actor-practice',
        title: '声優セリフ練習アプリ',
        description: 'ひとりでも掛け合いが練習できるアプリ。',
        type: 'website',
        url: request.original_url,
        image: image_url('logo_ogp.jpeg'),
        locale: 'ja_JP'
      },
      twitter: {
        card: 'summary',
        site: '@izumi60173364'
      }
    }
  end
end

app/views/layouts/_google_analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-35R2Y39FM9"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-35R2Y39FM9');
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= display_meta_tags(default_meta_tags) %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% if Rails.env.production? %>
      <%= render 'layouts/google_analytics' %>
    <% end %>
  </head>
  <body>
    <%= render 'shared/header' %>
    </br>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/plivacypolicy.html.erb
<div class="container-sm" style="width: 100%;">
</br>
  <h2>プライバシーポリシー</h2>
  <h2>取得する情報</h2>
  <h5>当サービスは、利用者から以下の情報を取得します。</br>・声、音声</h5>

  <h2>利用者の情報を利用する目的</h2>
  <h5>当サービスは、利用者から取得した情報を、以下の目的のために利用します。</br>・利用者の当サービスの利用履歴を管理するため</br>・当サービスにおける利用者の行動履歴を分析し、当サービスの維持改善に役立てるため</br>・以上の他、当サービスの提供、維持、保護及び改善のため</h5>

  <h2>第三者提供</h2>
  <h5>当サービスは、利用者から取得する情報のうち、個人データ（個人情報保護法第２条第６項）に該当するものついては、あらかじめ利用者の同意を得ずに、第三者（日本国外にある者を含みます。）に提供しません。
  但し、次の場合は除きます。</br>・個人データの取扱いを外部に委託する場合</br>・当サービスが買収された場合</br>・事業パートナーと共同利用する場合（具体的な共同利用がある場合は、その内容を別途公表します。）</br>・その他、法律によって合法的に第三者提供が許されている場合</h5>

  <h2>アクセス解析ツール</h2>
  <h5>当サービスは、利用者のアクセス解析のために、「Googleアナリティクス」を利用しています。Googleアナリティクスは、トラフィックデータの収集のためにCookieを使用しています。トラフィックデータは匿名で収集されており、個人を特定するものではありません。Cookieを無効にすれば、これらの情報の収集を拒否することができます。詳しくはお使いのブラウザの設定をご確認ください。Googleアナリティクスについて、詳しくは以下からご確認ください。
  </h5>
  <h6>https://marketingplatform.google.com/</br>about/analytics/terms/jp/</h6>

  <h2>プライバシーポリシーの変更</h2>

  <h5>当サービスは、必要に応じて、このプライバシーポリシーの内容を変更します。この場合、変更後のプライバシーポリシーの施行時期と内容を適切な方法により周知または通知します。</h5>

  <h2>お問い合わせ</h2>
  <h5>利用者の情報の削除をご希望の場合は、判定結果のURLを添えて以下のTwitter IDまでDMにてご連絡ください。</br>Twitter ID: @izumi60173364</h5>
  </br>
  </br>
  </br>
  <div class="text-center">
   <h4> <%= link_to 'TOPページへ', root_path , class: "link" %></h4>
  </div>
  </br>
</div>

app/views/quotes/_form.html.erb
<%= form_with model: @quote, local: true do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </div>
  
    <div>
      <%= form.label :quote_image %><br>
      <%= form.file_field :quote_image %>
    </div>

    <div>
    <%= form.label :opposite_voice %><br>
    <%= form.file_field :opposite_voice %>
  </div>

  <div>
  <%= form.label :emotion %><br>
  <%= form.text_field :emotion %>
  </div>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<%= render 'form' %>
<%= link_to 'ログアウト', 
  destroy_user_session_path,
  class: 'dropdown-item',
  method: :delete
%>

app/views/quotes/index.html.erb
<div class="text-center">
  <h2>練習したいセリフを選ぼう！</h2>
  </br>
  <div class="quote_emotion_index">
    <h2>【感情：怒り】 のセリフ</h2>
    <% @angry_quotes.each do |quote| %>
      <%= link_to quote_path(quote), class: 'btn btn-danger col-md-3 mb-3' do %>
         <%= quote.title %>
      <% end %>
    <% end %>
  </div>
  <div class="quote_emotion_index">
    <h2>【感情：悲しみ】 のセリフ</h2>
    <% @sad_quotes.each do |quote| %>
      <%= link_to quote_path(quote), class: 'btn btn-danger col-md-3 mb-3' do %>
         <%= quote.title %>
      <% end %>
    <% end %>
  </div>
  <div class="quote_emotion_index">
    <h2>【感情：喜び】 のセリフ</h2>
    <% @happy_quotes.each do |quote| %>
      <%= link_to quote_path(quote), class: 'btn btn-danger col-md-3 mb-3' do %>
        <%= quote.title %>
      <% end %>
    <% end %>
  </div>
  <div class="quote_emotion_index">
    <h2>【感情：嫌悪】 のセリフ</h2>
    <% @disgust_quotes.each do |quote| %>
      <%= link_to quote_path(quote), class: 'btn btn-danger col-md-3 mb-3' do %>
        <%= quote.title %>
      <% end %>
    <% end %>
  </div>
  <div class="quote_emotion_index">
    <h2>【感情：驚き】 のセリフ</h2>
    <% @surprise_quotes.each do |quote| %>
      <%= link_to quote_path(quote), class: 'btn btn-danger col-md-3 mb-3' do %>
        <%= quote.title %>
      <% end %>
    <% end %>
  </div>
  <div class="quote_emotion_index">
  <h2>【感情：平静】 のセリフ</h2>
  <% @neutral_quotes.each do |quote| %>
    <%= link_to quote_path(quote), class: 'btn btn-danger col-md-3 mb-3' do %>
      <%= quote.title %>
    <% end %>
  <% end %>
</div>
</div>

app/views/quotes/new.html.erb
<%= render 'form' %>
<%= link_to 'ログアウト', 
  destroy_user_session_path,
  class: 'dropdown-item',
  method: :delete
%>

app/views/quotes/show.html.erb
<div class="text-center">
  <div class="font-size">
    </br>
    <text><%= @quote.title %></text></br>
    <% if @quote.quote_image.present? %>
      <%= image_tag @quote.quote_image.url %>
    <% end %><br>
    <div class="usemic">
      <h4 class="alert alert-danger" id="warning_text">※↓最初にマイク使用許可ボタンを押してください↓※</h4>
      <button class = "btn btn-danger" id="start" >>>マイク使用許可<<</button>
    </div>
    <button class = "btn btn-dark w-25" id="rec" >録音開始</button>
    <button class = "btn btn-warning w-25" id="stop" >録音停止</button>
    <button class = "btn btn-secondary w-25" id="playid" >録音再生</button>
    </br>
    <text>※録音開始すると相手役の音声が流れます。音量注意</br>※録音できる秒数は相手役の音声含め30秒です</br>※30秒経過すると録音停止します</text>
    </br>
    <% if @quote.opposite_voice.present? %>
      <%= audio_tag(@quote.opposite_voice.url, id: "oppositevoice") %>
    <% end %>
    <audio id="play" controls></audio><br>
    <a id ="download" type="hidden"></a><br>
    <button class = "btn btn-danger " id="result" >>>>演技判定結果へ進む<<<</button><br>
    <%= form_with url:quote_results_path(@quote), id: "voiceform", local: true do |f| %>

      <%= f.hidden_field :quote_id, :value => @quote.id %>
      <%= f.hidden_field  :uuid  %>
      <%= f.hidden_field  :voice_data  %>
    <% end %>
    <br>
    <h4><%= link_to 'TOPページへ', root_path, class: "link"  %>&nbsp;&nbsp;&nbsp;
    <%= link_to 'セリフ一覧へ', quotes_path, class: "link"  %></h4>
    <br>
    <br>
  </div>
</div>
<%= javascript_pack_tag 'app' %>

app/views/results/show.html.erb
<div class="text-center">
  <h2><%= @result.quote.title %></h2>
  <% if @result.quote.quote_image.present? %>
    <%= image_tag @result.quote.quote_image.url %>
  <% end %><br>
  <br>
  <%=audio_tag("#{@result.voice_data.url}", controls: true) %>
  </br></br>
  
  <p class="text-danger">セリフ『<%= @result.quote.title %>』の</br>あなたの点数は<%= @display[:score] %>点です!(100点満点中)</p>
  <p><%= h(@display[:message]).gsub(/\n|\r|\r\n/, "<br>").html_safe %></p>
  <h4><%= link_to 'もう一度チャレンジ！', quote_path(@result.quote_id), class: "link"  %></h4>
  </br>
  <%= link_to 'Twitterであなたの演技をシェア！', "https://twitter.com/share?url=#{request.url}&text=セリフ『#{@result.quote.title}』にチャレンジしたよ！演技判定結果はリンクをクリック！%0a%0aひとりでも掛け合いのセリフ練習をしよう！%0a&hashtags=声優セリフ練習アプリ",class: 'btn btn-primary', title: 'Twitter', target: '_blank' %> 
  </br>
  </br>
  <h4><%= link_to 'TOPページへ', root_path , class: "link" %>&nbsp;&nbsp;&nbsp;
  <%= link_to 'セリフ一覧へ', quotes_path, class: "link"  %></h4>
  </br>
  </br>
</div>

app/views/shared/_footer.html.erb
<footer id="footer">
  <h4><%= link_to 'プライバシーポリシー',  privacypolicy_path, class: "link"  %>&nbsp;&nbsp;&nbsp;<%= link_to '利用規約', terms_path, class: "link"  %>&nbsp;&nbsp;&nbsp;<%= link_to '問い合わせ先', information_path, class: "link"  %></h4>
</footer>

app/views/shared/_header.html.erb
<header id="header">
  <%= link_to image_tag('logo.jpeg', size: '120x70'), root_path %>
</header>

app/views/static_pages/information.html.erb
<div class="container-sm" style="width: 100%;">
</br>
  <h2>問い合わせ先</h2>
  <h5>当サービスは、下記の者が運営しております。質問やご意見等ございましたら下記TwitterアカウントへDM下さいますようよろしくお願いします。</h5>
  <h5>Twitter ID: <%= link_to "@izumi60173364", "https://twitter.com/izumi60173364", class: "link" %></h5>
  <h5>匿名でのご意見もお待ちしています : <%= link_to "マシュマロ匿名ご意見", "https://marshmallow-qa.com/izumi60173364?utm_medium=url_text&utm_source=promotion", class: "link" %></h5>
  </br>
  </br>
</div>

app/views/static_pages/privacypolicy.html.erb
<div class="container-sm" style="width: 100%;">
</br>
  <h2>プライバシーポリシー</h2>
  <h2>取得する情報</h2>
  <h5>当サービスは、利用者から以下の情報を取得します。</br>・声、音声</h5>

  <h2>利用者の情報を利用する目的</h2>
  <h5>当サービスは、利用者から取得した情報を、以下の目的のために利用します。</br>・利用者の当サービスの利用履歴を管理するため</br>・当サービスにおける利用者の行動履歴を分析し、当サービスの維持改善に役立てるため</br>・以上の他、当サービスの提供、維持、保護及び改善のため</h5>

  <h2>第三者提供</h2>
  <h5>当サービスは、利用者から取得する情報のうち、個人データ（個人情報保護法第２条第６項）に該当するものついては、あらかじめ利用者の同意を得ずに、第三者（日本国外にある者を含みます。）に提供しません。
  但し、次の場合は除きます。</br>・個人データの取扱いを外部に委託する場合</br>・当サービスが買収された場合</br>・事業パートナーと共同利用する場合（具体的な共同利用がある場合は、その内容を別途公表します。）</br>・その他、法律によって合法的に第三者提供が許されている場合</h5>

  <h2>アクセス解析ツール</h2>
  <h5>当サービスは、利用者のアクセス解析のために、「Googleアナリティクス」を利用しています。Googleアナリティクスは、トラフィックデータの収集のためにCookieを使用しています。トラフィックデータは匿名で収集されており、個人を特定するものではありません。Cookieを無効にすれば、これらの情報の収集を拒否することができます。詳しくはお使いのブラウザの設定をご確認ください。Googleアナリティクスについて、詳しくは以下からご確認ください。
  </h5>
  <h6>https://marketingplatform.google.com/</br>about/analytics/terms/jp/</h6>

  <h2>プライバシーポリシーの変更</h2>

  <h5>当サービスは、必要に応じて、このプライバシーポリシーの内容を変更します。この場合、変更後のプライバシーポリシーの施行時期と内容を適切な方法により周知または通知します。</h5>

  <h2>お問い合わせ</h2>
  <h5>利用者の情報の削除をご希望の場合は、判定結果のURLを添えて以下のTwitter IDまでDMにてご連絡ください。</br>Twitter ID: @izumi60173364</h5>
  </br>
  </br>
  </br>
  <div class="text-center">
   <h4> <%= link_to 'TOPページへ', root_path , class: "link" %></h4>
  </div>
  </br>
</div>

app/views/static_pages/terms.html.erb
<div class="container-sm" style="width: auto;">
</br>
  <h2>利用規約</h2>
  <h5>この利用規約（以下，「本規約」といいます。）は，本運営者（以下，「運営者」といいます。）がこのウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。ユーザーの皆さまには，本規約に従って，本サービスをご利用いただきます。</h5>

  <h2>第1条（適用）</h2>
  <h5>1.本規約は，ユーザーと運営者との間の本サービスの利用に関わる一切の関係に適用されるものとします。</br>2.運営者は本サービスに関し，本規約のほか，ご利用にあたってのルール等，各種の定め（以下，「個別規定」といいます。）をすることがあります。これら個別規定はその名称のいかんに関わらず，本規約の一部を構成するものとします。</br>3.本規約の規定が前条の個別規定の規定と矛盾する場合には，個別規定において特段の定めなき限り，個別規定の規定が優先されるものとします。</h5>

  <h2>第2条（禁止事項）</h2>
  <h5>ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。</h5>
  <h5>1.法令または公序良俗に違反する行為</h5>
  <h5>2.犯罪行為に関連する行為</h5>
  <h5>3.本サービスの内容等，本サービスに含まれる著作権，商標権ほか知的財産権を侵害する行為</h5>
  <h5>4.運営者，ほかのユーザー，またはその他第三者のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為</h5>
  <h5>5.本サービスによって得られた情報を商業的に利用する行為</h5>
  <h5>6.運営者のサービスの運営を妨害するおそれのある行為</h5>
  <h5>7.不正アクセスをし，またはこれを試みる行為</h5>
  <h5>8.他のユーザーに関する個人情報等を収集または蓄積する行為</h5>
  <h5>9.不正な目的を持って本サービスを利用する行為</h5>
  <h5>10.本サービスの他のユーザーまたはその他の第三者に不利益，損害，不快感を与える行為</h5>
  <h5>11.他のユーザーに成りすます行為</h5>
  <h5>12.運営者が許諾しない本サービス上での宣伝，広告，勧誘，または営業行為</h5>
  <h5>13.面識のないユーザーとの出会いを目的とした行為</h5>
  <h5>14.運営者のサービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為</h5>
  <h5>15.その他，運営者が不適切と判断する行為</h5>

  <h2>第3条（本サービスの提供の停止等）</h2>
  <h5>1.運営者は，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。
  </h5>
  <h5>&nbsp;&nbsp;1.本サービスにかかるコンピュータシステムの保守点検または更新を行う場合</br>&nbsp;&nbsp;2.地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合</br>&nbsp;&nbsp;3.コンピュータまたは通信回線等が事故により停止した場合</br>&nbsp;&nbsp;4.その他，運営者が本サービスの提供が困難と判断した場合</h5>
  <h5>2.運営者は，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害についても，一切の責任を負わないものとします。</h5>
  
  <h2>第4条（利用制限および登録抹消）</h2>
  <h5>1.運営者は，ユーザーが以下のいずれかに該当する場合には，事前の通知なく，ユーザーに対して，本サービスの全部もしくは一部の利用を制限し，またはユーザーとしての登録を抹消することができるものとします。</h5>
  <h5>&nbsp;&nbsp;・運営者が本サービスの利用を適当でないと判断した場合</h5>
  <h5>2.運営者は，本条に基づき運営者が行った行為によりユーザーに生じた損害について，一切の責任を負いません。</h5>


  <h2>第5条（データの削除）</h2>
  <h5>運営者個人で契約しているストレージ容量超過の恐れがある場合、ユーザーの音声データ・判定結果等を削除させていただく場合があります。予めご了承下さい。</h5>

  <h2>第6条（保証の否認および免責事項）</h2>
  <h5>1.本サービスに事実上または法律上の瑕疵（安全性，信頼性，正確性，完全性，有効性，特定の目的への適合性，セキュリティなどに関する欠陥，エラーやバグ，権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。</h5>
  <h5>2.本サービスに起因してユーザーに生じたあらゆる損害について、運営者の故意又は重過失による場合を除き、一切の責任を負いません。ただし，本サービスに関する運営者とユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合，この免責規定は適用されません。</h5>
  <h5>3.前項ただし書に定める場合であっても，運営者は，運営者の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害のうち特別な事情から生じた損害（運営者またはユーザーが損害発生につき予見し，または予見し得た場合を含みます。）について一切の責任を負いません。また，運営者の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害の賠償は，ユーザーから当該損害が発生した月に受領した利用料の額を上限とします。</h5>
  <h5>4.運営者は，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。</h5>

  <h2>第7条（サービス内容の変更等）</h2>
  <h5>運営者は，ユーザーへの事前の告知をもって、本サービスの内容を変更、追加または廃止することがあり、ユーザーはこれを承諾するものとします。</h5>

  <h2>第8条（利用規約の変更）<h2>
  <h5>1.運営者は以下の場合には、ユーザーの個別の同意を要せず、本規約を変更することができるものとします。</h5>
  <h5>&nbsp;&nbsp;1.本規約の変更がユーザーの一般の利益に適合するとき。</br>&nbsp;&nbsp;2.本規約の変更が本サービス利用契約の目的に反せず、かつ、変更の必要性、変更後の内容の相当性その他の変更に係る事情に照らして合理的なものであるとき</h5>
  <h5>2.運営者はユーザーに対し、前項による本規約の変更にあたり、事前に、本規約を変更する旨及び変更後の本規約の内容並びにその効力発生時期を通知します。</h5>

  <h2>第9条（権利義務の譲渡の禁止）<h2>
  <h5>ユーザーは，運営者の書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。</h5>

  <h2>第10条（準拠法・裁判管轄）<h2>
  <h5>1.本規約の解釈にあたっては，日本法を準拠法とします。</br>2.本サービスに関して紛争が生じた場合には，運営者の居住地を管轄する裁判所を専属的合意管轄とします。</h5>

  <h2>第11条（演技の判定結果に関して）<h2>
  <h5>本サービスは感情解析AIを利用した評価基準となっており、実際の声優オーディション等で行われる評価基準とは異なります。判定結果が高得点であってもユーザーの声優/俳優としての将来を保証するものでは有りません。また、低得点のため演技の才能が全く無いということでもありません。養成所費用等の損害賠償責任は負いかねます、予めご了承下さい。</h5>

  <h2>第12条（演技判定の24時間上限回数について）<h2>
  <h5>本サービスは演技判定に感情解析AIのAPIを利用しており、24時間につき1000回の上限回数がございます。上限を超えてしまった場合、申し訳ございませんがそれ以上演技判定を行うことができません。その場合は時間を置いてからご利用頂きますようお願いいたします。</h5>

  </br>
  </br>
  </br>
  <div class="text-center">
    <h4> <%= link_to 'TOPページへ', root_path, class: "link"  %></h4>
  </div>
  </br>
</div>

app/views/static_pages/top.html.erb
<div class="bg-light p-3 p-sm-5 my-4 rounded" id="back">
 <div class="catch-text">
	<h1 id="first-text">“ひとり”でも</br>“掛け合い”が</br>練習できるアプリ。</h1>
	<%= link_to ">>>練習スタート<<<", quotes_path, class: "btn btn-danger btn-lg text-light", id: "startbtn"%>
  </div>
</div>
<footer id="footer">
<%= link_to 'Twitterシェアで応援', "https://twitter.com/share?url=#{request.url}%0a&text=ひとりでも掛け合いのセリフ練習をしよう！%0a&hashtags=声優セリフ練習アプリ",class: 'btn btn-outline-secondary', title: 'Twitter', target: '_blank' %>
</footer>